# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]
docs_dir = "site"
site_name = "Awesome Lists"
site_description = "Awesome Lists"
site_author="Jean-Michel Girard"
site_url = "https://jeanmgirard.github.io/Awesome/"
site_dir = "public" # required by gitlab
repo_url = "https://github.com/JeanMGirard/Awesome"
repo_name = "JeanMGirard/Awesome"
copyright = """
Copyright &copy; 2026 Jean-Michel Girard
"""
dev_addr = "localhost:3000"
edit_uri = "edit/main/awesome-lists/"
#extra_javascript = ["assets/scripts/extra.js"]
#extra_css = ["assets/css/extra.css"]
nav = [
  { "About" = "index.md" },
  { "Awesome Lists" = [
        "awesome-lists/ai.md",
        "awesome-lists/apis.md",
        "awesome-lists/chaos-engineering.md",
        "awesome-lists/cloud-architectures.md",
        "awesome-lists/communities.md",
        "awesome-lists/design-patterns.md",
        "awesome-lists/dev-environments.md",
        "awesome-lists/devops.md",
        "awesome-lists/docs.md",
        "awesome-lists/frontend.md",
        "awesome-lists/gitlab.md",
        "awesome-lists/go.md",
        "awesome-lists/iac.md",
        "awesome-lists/kubernetes.md",
        "awesome-lists/nodejs.md",
        "awesome-lists/powershell.md",
        "awesome-lists/principles.md",
        "awesome-lists/python.md",
        "awesome-lists/security.md",
        "awesome-lists/self-hosted.md",
        "awesome-lists/specifications.md",
        "awesome-lists/systems.md",
        "awesome-lists/terminals.md",
        "awesome-lists/ui-design.md"
    ]},
  { 'Others' = ["other-lists.md"]}
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
#variant = "classic"
#favicon = "images/favicon.png"
custom_dir = "site/overrides"
language = "en"
features = [
    "announce.dismiss",
    "content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    # "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
#    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    # "toc.follow",
    "toc.integrate",
]

[project.theme.icon]
logo = "lucide/star"
repo = "fontawesome/brands/github"
edit = "material/pencil"
view = "material/eye"


# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "slate"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "default"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# Extras
# ----------------------------------------------------------------------------
[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/JeanMGirard/Awesome"
#[[project.extra.social]]
#icon = "fontawesome/brands/gitlab"
#link = "https://x.com/zensical"

[project.extra.status]
# (new and deprecated are also supported)
draft = "Page is a work in progress and may be incomplete or inaccurate."

# ----------------------------------------------------------------------------
# Extensions
# ----------------------------------------------------------------------------
[project.markdown_extensions.toc]
permalink = "⚓︎"
toc_depth = 3

[project.markdown_extensions.toc.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.tables]

[project.markdown_extensions.def_list]

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

#[project.markdown_extensions.zensical.extensions.preview]
#configurations = [
#    { targets.include = [
#        "customization.md",
#        "setup/extensions/*"
#    ]}
#]
# ----------------------------------------------------------------------------
